> **Tutorial 3 (25054912)**


In [1]:
import numpy as np

In [7]:
# 1. Create a numpy array of size 2 x 2

array01 = np.array([[1, 2], [3, 4]])
print(array01)

[[1 2]
 [3 4]]


In [10]:
# 2. Create a random numpy array of size 3 x 4

array02 = np.random.random((3, 4))
print(array02)

[[0.08232978 0.96217623 0.00801471 0.41404836]
 [0.39321652 0.22457229 0.474776   0.2420542 ]
 [0.45338568 0.66570154 0.88902582 0.85281745]]


In [16]:
# 3. Create a numpy array of ones and a numpy array of zeroes

array03 = np.ones((3, 3))
print(array03)
print()

array04 = np.zeros((3, 3))
print(array04)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# 4. Create a random numpy array of size 6x3 and transpose it

array05 = np.random.random((6, 3))
print(array05.T)

[[0.19880046 0.51354854 0.38948156 0.36707787 0.98507425 0.90358293]
 [0.81572471 0.39673042 0.83893845 0.02840132 0.08473647 0.44830824]
 [0.80836378 0.27634895 0.44806062 0.49011735 0.29619031 0.07159819]]


In [31]:
# 5. Create two random numpy array of size n x p and p x m and then compute the dot product

n, p, m = 3, 4, 5

array06 = np.random.random((n, p))
array07 = np.random.random((p, m))

print("First Array (n x p):")
print(array06)
print()

print("Second Array (p x m):")
print(array07)
print()

dot_product = np.dot(array06, array07)

print("Dot Product (n x m):")
print(dot_product)

First Array (n x p):
[[0.21665163 0.31053866 0.4198319  0.81823466]
 [0.89819497 0.17516642 0.68061723 0.35299439]
 [0.30195964 0.0480108  0.55451728 0.98143985]]

Second Array (p x m):
[[0.81541484 0.62771444 0.33369605 0.49918011 0.73915904]
 [0.29893961 0.71333268 0.637671   0.44763172 0.54856466]
 [0.53554966 0.59925122 0.94401875 0.09790624 0.61716066]
 [0.31636202 0.20290578 0.76582138 0.7256499  0.1783713 ]]

Dot Product (n x m):
[[0.75319246 0.77512205 1.29326807 0.8820112  0.73554386]
 [1.26094403 1.16824719 1.32426875 0.84955812 1.24301329]
 [0.86803653 0.75522707 1.40646016 0.93869583 0.76682018]]


**Push to GitHub**

In [32]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [33]:
%cd /content/drive/MyDrive/git_repos/data-science-toolkit/

/content/drive/MyDrive/git_repos/data-science-toolkit


In [35]:
!git config --global user.email "aibragim288@gmail.com"
!git config --global user.name "mxnn-git"

In [ ]:
!cp -r "../../Colab Notebooks/Tutorial Submission" "./"